global using ContactsManagerAPI;
global using ContactsManagerAPI.Models;
global using Microsoft.AspNetCore.Http.HttpResults;
global using Microsoft.EntityFrameworkCore;
global using Carter;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.AspNetCore.Authorization;
global using System.Security.Claims;
global using Microsoft.IdentityModel.Tokens;
